server:
  port: 8000
  servlet:
    encoding:
      force-response: true
      charset: UTF-8
      force: true
      enabled: true

spring:
  session:
    timeout: 3600  # 세션 타임아웃 (초 단위)
  security:
    max-sessions: 1  # 동시 세션 제어
    max-sessions-prevents-login: true  # 최대 세션 수 초과 시 로그인 방지


  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true

  jpa:
    defer-datasource:
      initialization: true
      database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false